arcus-azure/arcus.webapi

src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.Logging/ExceptionHandlingMiddleware.cs
src/Arcus.WebApi.sln

This is the minimal functionality that I require for the moment in an ASP.NET API.   This functionality allows to log exceptions to multiple targets.
It surely needs to be extended to allow to add correlation-id's or other (custom) information.
I don't know what we're doing regarding documentation ?  
Anyway, usage of this middleware:
In `Startup.Configure` , this middleware can be added to the pipeline:
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
app.UseMiddleware<Arcus.WebApi.Logging.ExceptionHandlingMiddleware>();
}
```
The above statement will make sure that all unhandled exceptions are logged to all configured loggers.
To get the exceptions logged in AppInsights, logging should be configured like this when configuring the `IWebHost` (in …

Add middleware to log unhandled exceptions to various targets

---

docs/features/logging.md

I refered to `ApplicationSettings:TelemetryKey` instead of `ApplicationSettings:InstrumentationKey`

Refer to correct setting-names

---

docs/features/security/auth/shared-access-key.md

The `ICachedSecretProvider `should be a Singleton service instead of scoped per request.
#73

Improve documentation on authentication key filter

---

src/Arcus.WebApi.Unit/Security/Authentication/SharedAccessKeyAuthenticationAttributeTests.cs
src/Arcus.WebApi.Unit/Security/Authentication/SharedAccessKeyAuthenticationController.cs

The unit-tests for the SharedAccessKeyFilter were using the obsolete types.
Modified this to use the non-obsolete types.

Use non-obsolete types in unit-testing

---

build/nuget-release.yml

Official releases should use Package.Version as build version instead of based on time & revision

Official releases should use Package.Version as build version

---

build/nuget-release.yml

NuGet release should use correct repo names which is causing releases to fail.
Fixes https://github.com/arcus-azure/arcus.webapi/issues/88

NuGet release should use correct repo names

---

docs/features/correlation.md
src/Arcus.WebApi.Correlation/CorrelationMiddleware.cs
src/Arcus.WebApi.Correlation/CorrelationOptionsOperation.cs
src/Arcus.WebApi.Correlation/CorrelationOptionsTransaction.cs
src/Arcus.WebApi.Unit/Correlation/CorrelationTests.cs
src/Arcus.WebApi.Unit/Correlation/TraceIdentifierMiddleware.cs
src/Arcus.WebApi.Unit/Correlation/TraceIdentifierOptions.cs
src/Arcus.WebApi.Unit/Hosting/TestStartup.cs

Provide functions in the options to custommize the generation of the correlation ID's.
Closes #102 
Closes #103

FEAT: make correlation IDs consumer configurable

---

src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj

The Arcus.WebApi.Logging pckage used the Microsoft.AspNetCore.Mvc.Core package.
In this PR, the reference has been changed to Microsoft.AspNetCore.Mvc 2.2.0 instead of Microsoft.AspNetCore.Mvc.Core 2.2.2, to be more in line with the other projects in Arcus.   Next to that, referencing Mvc.Core 2.2.2 caused issues in a project that I'm working on.
Also, as described in this [article](https://andrewlock.net/converting-a-netstandard-2-library-to-netcore-3/#libraries-that-depend-on-asp-net-core-nuget-packages), the Microsoft.Extensions.* and Microsoft.AspNetCore.* packages are only referenced when targetting .NET Core 2.x
Before these changes get approved or are merged into master, I'd like to test them in one of the projects I'm working on.   Is there a preliminary (preview) nuget package …

Conditionally reference Packages or Framework, depending on the TargetFramework

---

build/templates/run-integration-tests.yml

The integration test template had a wrong project name resulting in the skipped running of the integration tests.

Fix - wrong integration test project name

---

docs/preview/features/logging.md
src/Arcus.WebApi.Logging/Correlation/CorrelationMiddleware.cs
src/Arcus.WebApi.Logging/Extensions/IApplicationBuilderExtensions.cs
src/Arcus.WebApi.Logging/VersionTrackingMiddleware.cs
src/Arcus.WebApi.Logging/VersionTrackingOptions.cs
src/Arcus.WebApi.Tests.Unit/Logging/StubAppVersion.cs
src/Arcus.WebApi.Tests.Unit/Logging/VersionTrackingMiddlewareTests.cs

Adds version tracking middleware with the necessary extension and options to influence its behavior.
Plus, the required tests to check if we can indeed customize the header name and application version.
Also tried to made it '_in-your-face_'-clear that it's a feature that should be handled with care.
Closes #180

Feature - add version tracking middleware

---

docs/preview/features/security/auth/certificate.md
docs/preview/features/security/auth/jwt.md
docs/preview/features/security/auth/shared-access-key.md
src/Arcus.WebApi.Security/Authentication/Certificates/BypassCertificateAuthenticationAttribute.cs
src/Arcus.WebApi.Security/Authentication/Certificates/CertificateAuthenticationFilter.cs
src/Arcus.WebApi.Security/Authentication/SharedAccessKey/BypassSharedAccessKeyAuthenticationAttribute.cs
src/Arcus.WebApi.Security/Authentication/SharedAccessKey/SharedAccessKeyAuthenticationFilter.cs
src/Arcus.WebApi.Security/Authorization/BypassJwtTokenAuthorizationAttribute.cs
src/Arcus.WebApi.Security/Authorization/JwtTokenAuthorizationFilter .cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/AllowAnonymousCertificateController.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/AllowAnonymousSharedAccessKeyController.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/BypassCertificateController.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/BypassSharedAccessKeyController.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/CertificateAuthenticationAttributeTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/SharedAccessKeyAuthenticationAttributeTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authorization/BypassJwtTokenAuthorizationController.cs
src/Arcus.WebApi.Tests.Unit/Security/Authorization/JwtTokenAutorizationFilterTests.cs
src/Arcus.WebApi.Tests.Unit/Security/BypassOnMethodController.cs

Provide the capability to bypass authentication and authorization with specific attributes and with the default `AllowAnonymous` attribute.
> Maybe it's good to merge later with #176 because it also adds logging to the API filters + provides an extension to safely retrieve a logger.
Closes #184

Feature - bypass API security filters with attributes

---

src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Security/Authentication/Certificates/CertificateAuthenticationFilter.cs
src/Arcus.WebApi.Security/Authentication/SharedAccessKey/SharedAccessKeyAuthenticationFilter.cs
src/Arcus.WebApi.Security/Authorization/JwtTokenAuthorizationFilter .cs

Now that we have extracted the SQL package in the Observability repo (https://github.com/arcus-azure/arcus.observability/issues/131), we can use the `.LogSecurityEvent` instead.

Feature - use `.LogSecurityEvent` for security types

---

src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs

Ensure the request body is tracked if need be, and do it before running any other middleware so that the stream cannot be disposed of already.
That's the root cause of our problem where it tries to get the stream position, but somebody else already disposed of it (which is out of Arcus control, so we have to coop with it).
Closes #165

fix: Ensure request body is tracked

---

docs/preview/features/logging.md
src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs
src/Arcus.WebApi.Logging/SkipRequestTrackingAttribute.cs
src/Arcus.WebApi.Tests.Unit/Hosting/EchoController.cs
src/Arcus.WebApi.Tests.Unit/Hosting/TestApiServer.cs
src/Arcus.WebApi.Tests.Unit/Logging/RequestTrackingMiddlewareTests.cs
src/Arcus.WebApi.Tests.Unit/Logging/SkipRequestTrackingOnClassController.cs
src/Arcus.WebApi.Tests.Unit/Logging/SkipRequestTrackingOnMethodController.cs
src/Arcus.WebApi.Tests.Unit/Logging/VersionTrackingMiddlewareTests.cs

Adds a `SkipRequestTrackingAttribute` so consumers can pick and choose which endpoints should be tracked and which not.
Relates to #200

Feature - skip request tracking attribute

---

src/Arcus.WebApi.Logging/RequestTrackingOptions.cs
src/Arcus.WebApi.Tests.Unit/Logging/RequestTrackingMiddlewareTests.cs

Seems like a good idea to omit this Azure API Management default subscription key header in our request tracking middleware.

chore: omit (by default) API Management default subscription key header

---

docs/features/logging.md
docs/preview/features/logging.md
docs/v1.1.0/features/logging.md
docs/v1.2.0/features/logging.md

Moved the `.UseExceptionHandling` after the `.UseRequestTracking` in the docs to show that unhandled exceptions that results in 50 response status codes will otherwise not be tracked.
Relates to #208

fix: move exceptionhandling after requesttracking in docs

---

docs/preview/features/logging.md
src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs
src/Arcus.WebApi.Logging/RequestTrackingOptions.cs
src/Arcus.WebApi.Tests.Unit/Logging/RequestTrackingMiddlewareTests.cs

Make sure that we can exclude entire HTTP routes from the request tracking options instead of using attributes.
Closes #217

feat: omit routes in request tracking

---

docs/preview/features/logging.md
src/Arcus.WebApi.Logging/RequestTrackingAttribute.cs
src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs
src/Arcus.WebApi.Logging/RequestTrackingOptions.cs
src/Arcus.WebApi.Logging/StatusCodeRange.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/DiscardedStatusCodeOnClassController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/DiscardedStatusCodeOnMethodController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/ExcludeFilterIgnoredWhileExcludedOnClassController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/ExcludeFilterRequestTrackingOnMethodController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/ExcludeFilterUsedWhileExcludedOnClassController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/ExcludeRequestTrackingOnClassController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/ExcludeRequestTrackingOnMethodController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/StubbedStatusCodeController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/TrackedClientErrorStatusCodesOnClassController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/TrackedNotFoundAndClientErrorsSubsetStatusCodesOnClassController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/TrackedNotFoundStatusCodeOnClassController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/TrackedServerErrorStatusCodesOnMethodController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/TrackedStatusCodeOnClassController.cs
src/Arcus.WebApi.Tests.Unit/Logging/Controllers/TrackedStatusCodeOnMethodController.cs
src/Arcus.WebApi.Tests.Unit/Logging/RequestTrackingAttributeTests.cs
src/Arcus.WebApi.Tests.Unit/Logging/RequestTrackingMiddlewareTests.cs
src/Arcus.WebApi.Tests.Unit/Logging/StatusCodeRangeTests.cs

Provide the capability to add a range of HTTP status codes on both the request tracking options as in the `[RequestTracking]` attirbute.
Closes #216

feat: add HTTP status code ranges to request tracking

---

src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs
src/Arcus.WebApi.Tests.Unit/Logging/RequestTrackingMiddlewareTests.cs

Add extra `null`-check before we check if the response status code is within the configured range.
Relates to #216

fix: add extra null-check for HTTP status code range

---

src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs
src/Arcus.WebApi.Tests.Unit/Hosting/EmptyApiServer.cs
src/Arcus.WebApi.Tests.Unit/Hosting/TestApiServer.cs
src/Arcus.WebApi.Tests.Unit/Logging/RequestTrackingMiddlewareTests.cs

In this test project, the in-memory hosting functionality wasn't acting the same way as the 'real-life' hosting. Meaning, that the `IEndpointFeature` wasn't always the same structure, or available in the same way the test project was.
This was discovered by releasing the v1.3 version.
This can be reproduced by adding an 'invalid' endpoint feature to the in-memory hosting project. This allows us to see what's wrong: the request tracking middleware wasn't correctly handling `null` values completely.
It's worth noting that we should invest in maybe a more 'real life' approach where we use the `Host.CreateDefaultBuilder` directly to limit the gap between testing and production.

fix: handle invalid endpoint features in request tracking

---

docs/preview/features/logging.md
docs/v1.3.0/features/logging.md

Minor correction in the documentation:
`UseRequestRouting` was mentionned instead of `UseRequestTracking` in the comments on how to use this feature.

docs: UseRequestTracking instead of UseRequestRouting

---

src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Tests.Integration/Logging/RequestTrackingMiddlewareTests.cs

Let's use NuGet version ranges to include Arcus dependencies so we can more easily support multiple Arcus packages in a single project.
Relates to https://github.com/arcus-azure/arcus/issues/129

fix: use Arcus NuGet version ranges

---

docs/index.md
docs/preview/index.md
docs/v1.1.0/index.md
docs/v1.2.0/index.md
docs/v1.3.0/index.md

Adds missing 'Tracking application version' logging section to the index landing pages of all the versions that included this.

docs: add app tracking to landing page

---

docs/preview/features/correlation.md
src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging.Core/Correlation/CorrelationInfoUpstreamServiceOptions.cs
src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelation.cs
src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationInfoOptions.cs
src/Arcus.WebApi.Logging.Core/Extensions/IServiceCollectionExtensions.cs
src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.Tests.Integration/Logging/CorrelationMiddlewareTests.cs
src/Arcus.WebApi.Tests.Integration/Logging/RequestTrackingMiddlewareTests.cs
src/Arcus.WebApi.Tests.Integration/Logging/TelemetryCorrelationTests.cs
src/Arcus.WebApi.Tests.Unit/Arcus.WebApi.Tests.Unit.csproj
src/Arcus.WebApi.Tests.Unit/Logging/HttpCorrelationTests.cs

Adding an operation parent ID functionality to the correlation middleware to extract based on configured options the combination 'operation parent ID/operation ID' from the request header, and registering it as the scoped correlation info of the request.
Relates to https://github.com/arcus-azure/arcus.webapi/issues/233

feat: add operation parent ID to correlation middleware

---

docs/preview/features/security/auth/jwt.md
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Security/Authentication/JwtBearer/Extensions/AuthenticationBuilderExtensions.cs
src/Arcus.WebApi.Tests.Integration/Arcus.WebApi.Tests.Integration.csproj
src/Arcus.WebApi.Tests.Integration/Fixture/TestApiServer.cs
src/Arcus.WebApi.Tests.Integration/Security/Authentication/Controllers/AuthorizedController.cs
src/Arcus.WebApi.Tests.Integration/Security/Authentication/JwtBearerAuthenticationTests.cs

Add updated `.AddJwtBearer` extension to have access to the `IServiceProvider` and the Arcus secret store.
Closes #271

feat: add jwt bearer token extension for secret store

---

src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs

Some overloaded methods were using invalid XML code docs.
Fixed now.

fix: request tarcking xml docs

---

docs/versioned_docs/version-v1.1.0/features/correlation.md
docs/versioned_docs/version-v1.2.0/features/correlation.md
docs/versioned_docs/version-v1.3.0/features/correlation.md
docs/versioned_docs/version-v1.4.0/features/correlation.md

This was already fixed in the preview docs, but not in the published ones.
I think, due to the fact that it's about a sub-title and not a style 1 header, we can skip the redirects here.
Closes #295

fix: use correlation in sub-title io secret store

---

src/Arcus.WebApi.Logging/Extensions/HttpCorrelationEnricherExtensions.cs

Adds a more dev-friendly exception message when the `IHttpContextAccessor` is missing from the registered services.
Closes #285

chore: add dev-friendly msg for missed http ctx accessor

---

src/Arcus.WebApi.Logging.AzureFunctions/Extensions/IServiceCollectionExtensions.cs
src/Arcus.WebApi.Tests.Runtimes.AzureFunction/Startup.cs
src/Arcus.WebApi.Tests.Unit/Arcus.WebApi.Tests.Unit.csproj
src/Arcus.WebApi.Tests.Unit/Logging/IFunctionsHostBuilderTests.cs

Adds a dedicated extension for adding HTTP correlation services to an Azure Functions project, using the new `HttpCorrelationInfoOptions` instead.
Closes #298

feat: add http correlation extension for az func

---

.github/workflows/codeql-analysis.yml
src/Arcus.WebApi.Tests.Integration/Security/Authentication/Fixture/SelfSignedCertificate.cs
src/Arcus.WebApi.Tests.Integration/Security/Authorization/JwtTokenAuthorizationFilterTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authorization/JwtTokenReaderTests.cs

Adds CodeQL code scanning.
Relates to https://github.com/arcus-azure/arcus/issues/197

chore: add codeql scanning

---

src/Arcus.WebApi.All/Arcus.WebApi.All.csproj
src/Arcus.WebApi.Hosting/Arcus.WebApi.Hosting.csproj
src/Arcus.WebApi.Logging.AzureFunctions/Arcus.WebApi.Logging.AzureFunctions.csproj
src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.OpenApi.Extensions/Arcus.WebApi.OpenApi.Extensions.csproj
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj

Adds the GitHub README file to the NuGet package generation of the projects.
Adds feature docs project URL instead of GitHub URL to NuGet package.
Relates to arcus-azure/arcus#209
Relates to arcus-azure/arcus#208

chore: add readme and proj url to nuget pkg

---

src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs

The RequestTracking middleware was not logging the correct start date/time.  Instead of the actual start date and time of the request , the current date/time was used.
#333

Fix start-time of WebApi request-tracking

---

docs/preview/features/security/auth/jwt.md
src/Arcus.WebApi.Security/Authorization/Extensions/FilterCollectionExtensions.cs
src/Arcus.WebApi.Security/Authorization/Extensions/MvcOptionsExtensions.cs
src/Arcus.WebApi.Tests.Integration/Security/Authorization/JwtTokenAuthorizationFilterTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authorization/FilterCollectionExtensionsTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authorization/MvcOptionsExtensionsTests.cs

Change target type of JWT authorization filter to the MVC options instead.
Relates to #329

feat: change jwt target type

---

src/Arcus.WebApi.Tests.Integration/Hosting/Formatting/MvcOptionsExtensionsTests.cs

Circumvent non-ASCII characters in the JSON formatting integration tests so that we don't fail on equalization assertion failures due to the fact that the non-ASCII characters were escaped in the returned string but not in the original string.
Closes #352

test: circumvent non-ascii chars in json formatting tests

---

docs/preview/features/correlation.md
src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationMessageHandler.cs
src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationProperties.cs
src/Arcus.WebApi.Logging.Core/Extensions/HttpClientExtensions.cs
src/Arcus.WebApi.Logging.Core/Extensions/IHttpClientBuilderExtensions.cs
src/Arcus.WebApi.Tests.Integration/Logging/Controllers/CorrelationController.cs
src/Arcus.WebApi.Tests.Integration/Logging/Controllers/ServiceAController.cs
src/Arcus.WebApi.Tests.Integration/Logging/Controllers/ServiceBController.cs
src/Arcus.WebApi.Tests.Integration/Logging/Fixture/HttpAssert.cs
src/Arcus.WebApi.Tests.Integration/Logging/Fixture/HttpAssertProvider.cs
src/Arcus.WebApi.Tests.Integration/Logging/Fixture/HttpAssertServiceCollectionExtensions.cs
src/Arcus.WebApi.Tests.Integration/Logging/HttpCorrelationMessageHandlerTests.cs
src/Arcus.WebApi.Tests.Unit/Arcus.WebApi.Tests.Unit.csproj
src/Arcus.WebApi.Tests.Unit/Logging/Fixture/AssertHttpMessageHandler.cs
src/Arcus.WebApi.Tests.Unit/Logging/Fixture/DefaultHttpMessageHandlerBuilder.cs
src/Arcus.WebApi.Tests.Unit/Logging/Fixture/StubHttpCorrelationInfoAccessor.cs
src/Arcus.WebApi.Tests.Unit/Logging/Fixture/StubHttpMessageHandler.cs
src/Arcus.WebApi.Tests.Unit/Logging/HttpClientExtensionsTests.cs
src/Arcus.WebApi.Tests.Unit/Logging/HttpCorrelationTrackingTests.cs
src/Arcus.WebApi.Tests.Unit/Logging/HttpMessageHandlerTests.cs

Adds HTTP correlation tracking to sending side:
- as a `HttpMessageHandler` that can be added to the registered `IHttpClientFactory`
- as an extension on the `HttpClient` for existings instances
Closes #257
Closes #258

feat: add http client correlation tracking

---

docs/preview/features/security/auth/shared-access-key.md
src/Arcus.WebApi.Security/Authentication/SharedAccessKey/Extensions/FilterCollectionExtensions.cs
src/Arcus.WebApi.Security/Authentication/SharedAccessKey/Extensions/MvcOptionsExtensions.cs
src/Arcus.WebApi.Tests.Integration/Security/Authentication/SharedAccessKeyAuthenticationFilterTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/MvcOptionsExtensionsTests.cs

Change the target type of the shared access key authentcation from the `FilterCollection` (`mvcOptions.Filters`) to `MvcOptions` (`services.AddControllers(mvcOptions => ...)`).
Relates to #329

feat: change sharedaccesskey target type

---

docs/preview/features/security/auth/certificate.md
src/Arcus.WebApi.Security/Authentication/Certificates/CertificateAuthenticationConfigBuilder.cs
src/Arcus.WebApi.Security/Authentication/Certificates/Extensions/FilterCollectionExtensions.cs
src/Arcus.WebApi.Security/Authentication/Certificates/Extensions/MvcOptionsExtensions.cs
src/Arcus.WebApi.Tests.Integration/Security/Authentication/CertificateAuthenticationFilterTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/CertificateAuthenticationConfigBuilderTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/CertificateAuthenticationFilterTests.cs

Change target type of the certificate authentication to the MVC options itself.
Relates to #329

feat: change certificate auth target type

---

src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationMessageHandler.cs
src/Arcus.WebApi.Logging.Core/Extensions/IHttpClientBuilderExtensions.cs
src/Arcus.WebApi.Tests.Unit/Logging/IHttpClientBuilderExtensionsTests.cs

Improve exception message when registering the HTTP client with HTTP correlation tracking.
Follow-up #346

chore: improve http client correlation tracking exception message

---

src/Arcus.WebApi.Logging.AzureFunctions/Extensions/IServiceCollectionExtensions.cs

Use the empty HTTP correlation extension in Azure Functions.

chore: make http correlation az func available

---

src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelation.cs

Use `Trace` io `Warning` to write diagnostic message about missing `Request-Id` as this is sometimes correct (like in the initial request).
Closes #369

(❗) chore: update missing request id warning to trace

---

.github/workflows/codeql-analysis.yml
docs/preview/features/correlation.md
src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationMessageHandler.cs
src/Arcus.WebApi.Logging.Core/Extensions/HttpClientExtensions.cs
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Tests.Integration/Arcus.WebApi.Tests.Integration.csproj
src/Arcus.WebApi.Tests.Integration/Logging/Controllers/ServiceAController.cs
src/Arcus.WebApi.Tests.Integration/Logging/HttpCorrelationMessageHandlerTests.cs
src/Arcus.WebApi.Tests.Runtimes.AzureFunction/Dockerfile
src/Arcus.WebApi.Tests.Unit/Logging/HttpClientExtensionsTests.cs
src/Arcus.WebApi.Tests.Unit/Logging/HttpCorrelationClientOptionsTests.cs
src/Arcus.WebApi.Tests.Unit/Logging/HttpMessageHandlerTests.cs

Enhances HTTP client correlation options to pass telemetry context so that the following tracked HTTP dependency has additional custom dimensions.
Closes #370

(❗) feat: add telemetry context to http client correlation options

---

README.md

The `Arcus.WebApi.All` package is deprecated.

docs: use correct example package in README

---

docs/preview/03-Features/logging.md

Remove the 'Application Insights' section in the Web API logging page as this is a duplicate of the more thoroughly explained Arcus Observability feature documentation.
Closes #368

docs: remove appinsights logging section

---

docs/preview/03-Features/security/auth/certificate.md
src/Arcus.WebApi.Security/Authentication/Certificates/CertificateAuthenticationAttribute.cs
src/Arcus.WebApi.Security/Authentication/Certificates/CertificateAuthenticationFilter.cs
src/Arcus.WebApi.Security/Authentication/Certificates/Extensions/IServiceCollectionExtensions.cs
src/Arcus.WebApi.Security/Authentication/Certificates/Extensions/MvcOptionsExtensions.cs
src/Arcus.WebApi.Security/Authentication/Certificates/NullCertificateAuthenticationValidator.cs
src/Arcus.WebApi.Security/Authentication/Certificates/SecretProviderValidationLocation.cs
src/Arcus.WebApi.Security/Authentication/SharedAccessKey/SharedAccessKeyAuthenticationFilter.cs
src/Arcus.WebApi.Tests.Integration/Security/Authentication/CertificateAuthenticationAttributeTests.cs
src/Arcus.WebApi.Tests.Integration/Security/Authentication/CertificateAuthenticationFilterTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/IServiceCollectionExtensionsTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authentication/MvcOptionsExtensionsTests.cs

Simplify the registration of the certificate authentication validator by either passing the configuration directly during the global certificate authentication filter or by using the new extension.
Closes #350

feat: simplify cert auth validation registration

---

src/Arcus.WebApi.Hosting.AzureFunctions/Formatting/AzureFunctionsJsonFormattingMiddleware.cs
src/Arcus.WebApi.Tests.Unit/Hosting/Formatting/AzureFunctionsJsonFormattingMiddlewareTests.cs

Add allow all header value to Azure Functions JSON formatting middleware.
Closes #393

feat: add allow all to az func middleware

---

src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationTemplate.cs
src/Arcus.WebApi.Logging.Core/Extensions/IHeaderDictionaryExtensions.cs
src/Arcus.WebApi.Tests.Integration/Logging/W3CCorrelationMiddlewareTests.cs

Retrieve transaction and operation ID after the Activity is started when there is no above parent from the incoming HTTP request.
Closes https://github.com/arcus-azure/arcus.webapi/issues/408

fix: service correlation w/ single api (❗) 

---

src/Arcus.WebApi.Hosting.AzureFunctions/Formatting/AzureFunctionsJsonFormattingMiddleware.cs
src/Arcus.WebApi.Tests.Unit/Hosting/Formatting/AzureFunctionsJsonFormattingMiddlewareTests.cs

We need to make sure that we also accept headers with a factor weighting (`q=`).
Closes #405

fix: relaxed allow header json formatting

---

src/Arcus.WebApi.Security/Authorization/Jwt/JwtTokenReader.cs

It was not clear from the name of the `applicationId` parameter of the JwtTokenReader ctor how that parameter was being used.
Turns out that it was used to check if the Jwt Token matches a specific value for the audience claim.  Therefore, the parameter has been renamed to `audience`.
Closes #399

refactor: rename the applicationId parameter to audience on the ctor of JwtTokenReader

---

src/Arcus.WebApi.Logging.AzureFunctions/Extensions/IServiceCollectionExtensions.cs
src/Arcus.WebApi.Tests.Unit/Logging/IFunctionsHostBuilderTests.cs

Use still `HttpCorrelation` in deprecated in-process Azure Functions with deprecated Hierachical HTTP correlation system.
Relates to #422

fix: use still http correlation instance w/ hierarhical (❗)

---

docs/preview/03-Features/correlation.md
docs/versioned_docs/version-v1.7.0/03-Features/correlation.md

Remove the options configuration of the non-configurable `traceparent` in the HTTP correlation options. This is only available in the Hierarchical setup.

docs: remove non-configurable traceparent http header

---

build/ci-build.yml
build/nuget-release.yml
build/templates/run-docker-integration-tests.yml
build/variables/build.yml
src/Arcus.WebApi.Logging.AzureFunctions/Arcus.WebApi.Logging.AzureFunctions.csproj
src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging.Core/Correlation/CorrelationInfoUpstreamServiceOptions.cs
src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelation.cs
src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationInfoOptions.cs
src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Tests.Integration/Arcus.WebApi.Tests.Integration.csproj
src/Arcus.WebApi.Tests.Integration/Logging/AzureFunctionsJsonFormattingDockerTests.cs
src/Arcus.WebApi.Tests.Unit/Arcus.WebApi.Tests.Unit.csproj

Use the new major release versions of the Arcus packages Observability and Security, both with the .NET 8 support.
Relates to https://github.com/arcus-azure/arcus/issues/311

chore: use new major versions of arcus packages
