src/Arcus.WebApi.All/Arcus.WebApi.All.csproj
src/Arcus.WebApi.All/README.md
src/Arcus.WebApi.sln

Provide empty boilerplate

---

src/Arcus.WebApi.All/Arcus.WebApi.All.csproj

Fix broken build

---

src/Arcus.WebApi.Logging/ExceptionHandlingMiddleware.cs

Improve documentation of library

Improve documentation

---

src/Arcus.WebApi.All/Arcus.WebApi.All.csproj

Arcus.WebApi.All should depend on Arcus.WebApi.Logging

Arcus.WebApi.All should depend on Arcus.WebApi.Logging

---

.github/CODEOWNERS
README.md
docs/index.md

- Configure Codeowners (@fgheysels, @stijnmoreels & myself)
- Introduce NuGet badges in README & docs
Closes #4, #1

Configure Codeowners & Introduce NuGet badges

---

docs/features/shared-access-key.md
docs/index.md

Adds features documentation for the shared access key authentication
that can be both configured on global and local level by an attribute
and authentication filter.
#12

DOC: add feature docs for shared access key authentication

---

docs/features/logging.md
docs/features/shared-access-key.md

Use more reading-friendly headers in docs

---

src/Arcus.WebApi.Security/Authentication/CertificateAuthenticationConfig.cs
src/Arcus.WebApi.Security/Authentication/CertificateAuthenticationFilter.cs
src/Arcus.WebApi.Security/Authentication/CertificateAuthenticationValidator.cs
src/Arcus.WebApi.Security/Authentication/ConfigurationValidationLocation.cs
src/Arcus.WebApi.Security/Authentication/Interfaces/IX509ValidationLocation.cs
src/Arcus.WebApi.Security/Authentication/SecretProviderValidationLocation.cs
src/Arcus.WebApi.Unit/Security/Doubles/StubX509ValidationLocation.cs

REFACTOR: suffix async methods with '...Async'

---

docs/features/logging.md
docs/features/openapi/security-definitions.md
docs/features/security/auth/certificate.md
docs/features/security/auth/shared-access-key.md

Docs - Add missing back buttons

---

build/ci-build.yml

Adds the CI build as a YAML build (without the Github Package Registr y for now).

FEAT: create YAML file for CI build

---

build/myget-release.yml

FEAT: add YAML release to MyGet

---

src/Arcus.WebApi.Security.Authentication/Certificates/CertificateAuthenticationFilter.cs
src/Arcus.WebApi.Unit/Security/Authentication/CertificateAuthenticationAttributeTests.cs

Load the client certificate from mutual TLS authentication from the
header with the name 'X-ARR-ClientCert'.
Closes #72

FEAT: load client certificate from AppService header

---

build/nuget-release.yml

Adds NuGet release
Relates to #47

CHORE: add NuGet release

---

build/nuget-release.yml

FIX: use extension on publish NuGet YAML template

---

build/ci-build.yml
build/nuget-release.yml
src/Arcus.WebApi.OpenApi.Extensions/Arcus.WebApi.OpenApi.Extensions.csproj
src/Arcus.WebApi.OpenApi.Extensions/OAuthAuthorizeOperationFilter.cs
src/Arcus.WebApi.Unit/Arcus.WebApi.Unit.csproj
src/Arcus.WebApi.Unit/Hosting/TestApiServer.cs
src/Arcus.WebApi.Unit/Hosting/TestStartup.cs

FEAT: YAML build on .NET Core 2.2 & 3.0 SDK

---

docs/_site/features/logging.html
docs/_site/features/openapi/security-definitions.html
docs/_site/features/security/auth/certificate.html
docs/_site/features/security/auth/shared-access-key.html
docs/_site/index.html
docs/features/security/auth/shared-access-key.md

Streamline shared access key docs

---

src/Arcus.BackgroundJobs/Arcus.BackgroundJobs.csproj
src/Arcus.BackgroundJobs/CloudEvent/CloudEventBackgroundJob.cs
src/Arcus.BackgroundJobs/CloudEvent/CloudEventBackgroundJobOptions.cs
src/Arcus.WebApi.Jobs/KeyVault/AutoInvalidateKeyVaultSecretJob.cs
src/Arcus.WebApi.Jobs/KeyVault/IServiceCollectionExtensions.cs
src/Arcus.WebApi.sln

FEAT: move 'CloudEventBackgroundJob' to sep project

---

src/Arcus.WebApi.All/Arcus.WebApi.All.csproj
src/Arcus.WebApi.Security.Authentication/Arcus.WebApi.Security.Authentication.csproj
src/Arcus.WebApi.Security.Authorization/Arcus.WebApi.Security.Authorization.csproj
src/Arcus.WebApi.Security.Authorization/AzureManagedIdentityAuthorizationFilter.cs
src/Arcus.WebApi.Security.Authorization/Jwt/IJwtTokenReader.cs
src/Arcus.WebApi.Security.Authorization/Jwt/JwtTokenReader.cs
src/Arcus.WebApi.Unit/Arcus.WebApi.Unit.csproj
src/Arcus.WebApi.Unit/Security/Authentication/CertificateAuthenticationFilterTests.cs
src/Arcus.WebApi.Unit/Security/Authorization/AzureManagedIdentityAuthorizationFilterTests.cs
src/Arcus.WebApi.Unit/Security/Authorization/JwtTokenReaderTests.cs
src/Arcus.WebApi.sln

Provide Azure Managed Identity authorization which can be used with services such as Azure API Management.
Relates to https://github.com/arcus-azure/arcus.webapi/issues/120

Provide Azure Managed Identity authorization foundation

---

docs/features/telemetry.md
docs/index.md

Docs - update feature docs with telemetry serilog correlation enricher

---

src/Arcus.WebApi.Correlation/Arcus.WebApi.Correlation.csproj
src/Arcus.WebApi.Security.Authentication/Arcus.WebApi.Security.Authentication.csproj
src/Arcus.WebApi.Security.Authorization/Arcus.WebApi.Security.Authorization.csproj

Relates to https://github.com/arcus-azure/arcus/issues/50

Chore - update WebApi projects with netcore3.0

---

src/Arcus.WebApi.Security.Authorization/AzureManagedIdentityAuthorizationFilter.cs
src/Arcus.WebApi.Security.Authorization/Jwt/IJwtTokenReader.cs
src/Arcus.WebApi.Security.Authorization/Jwt/JwtTokenReader.cs
src/Arcus.WebApi.Unit/Security/Authorization/JwtTokenReaderTests.cs

Provide configuration options for Managed Identity authorization validation.
Next PR will finalize this with docs, registration and JWT tests.
Relates to #120

Provide configuration options for Managed Identity authorization validation

---

docs/features/correlation.md
src/Arcus.WebApi.Correlation/Arcus.WebApi.Correlation.csproj
src/Arcus.WebApi.Correlation/HttpCorrelationEnricherExtensions.cs

Closes https://github.com/arcus-azure/arcus.webapi/issues/137
Relates to https://github.com/arcus-azure/arcus.observability/issues/69

Feature - add '.WithHttpCorrelationInfo' to Serilog enrichment extensions

---

src/Arcus.WebApi.Security.Authorization/AzureManagedIdentityAuthorizationFilter.cs
src/Arcus.WebApi.Tests.Unit/Security/Authorization/AzureManagedIdentityAuthorizationFilterTests.cs

Simplify managed identity filter to get it working (roughly)

---

src/Arcus.WebApi.Security/Authorization/AzureManagedIdentityAuthorizationFilter.cs
src/Arcus.WebApi.Security/Authorization/Jwt/IJwtTokenReader.cs
src/Arcus.WebApi.Security/Authorization/Jwt/JwtTokenReader.cs
src/Arcus.WebApi.Tests.Unit/Arcus.WebApi.Tests.Unit.csproj
src/Arcus.WebApi.Tests.Unit/Hosting/HealthController.cs
src/Arcus.WebApi.Tests.Unit/Hosting/TestOpenIdServer.cs
src/Arcus.WebApi.Tests.Unit/Security/Authorization/AzureManagedIdentityAuthorizationFilterTests.cs

Testing - add tests for Azure Managed Identity authorization filter

---

docs/preview/features/security/auth/jwt.md
src/Arcus.WebApi.Security/Authorization/Extensions/FilterCollectionExtensions.cs
src/Arcus.WebApi.Security/Authorization/JwtTokenAuthorizationFilter .cs
src/Arcus.WebApi.Security/Authorization/JwtTokenAuthorizationOptions.cs
src/Arcus.WebApi.Tests.Unit/Hosting/TestApiServer.cs
src/Arcus.WebApi.Tests.Unit/Security/Authorization/AzureManagedIdentityAutorizationFilterTests.cs
src/Arcus.WebApi.Tests.Unit/Security/Authorization/JwtTokenAutorizationFilterTests.cs

Use configuration approach for JWT Token authorization.
Relates to #120

Use configuration approach for JWT Token authorization

---

src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Tests.Unit/Logging/RequestTrackingMiddlewareTests.cs

We can update the Arcus dependencies here bc it's not breaking changes, right?

Feature - update observability & security packages

---

src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs

Don't dispose stream when logging request bodies

---

src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelation.cs
src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs

Provide extra trace logging when making decisions based on consumer-configured options. Explaining why the functionality behaves based on consumer-input so debugging and defect localization is more easily done.

Feature - add trace logging during correlation & request tracking

---

README.md

Update README with more correct installation message with available common packages.
Relates to https://github.com/arcus-azure/arcus/issues/92

Docs - update README with more correct installation message

---

docs/preview/features/logging.md
src/Arcus.WebApi.Logging/RequestTrackingMiddleware.cs

Leftover comments from the merged #202 PR.

fix: skip request tracking attribute

---

.github/semantic.yml

Make sure that Sematic only validates the PR title.
Relates to https://github.com/arcus-azure/arcus/issues/121

fix: Add Semantic config file

---

docs/features/security/auth/shared-access-key.md
docs/preview/features/security/auth/shared-access-key.md

Formatting for shared access key is broken in rendered result

fix: Formatting for shared access key is broken

---

docs/features/security/auth/certificate.md
docs/features/security/auth/shared-access-key.md
docs/preview/features/security/auth/certificate.md
docs/preview/features/security/auth/shared-access-key.md
docs/v1.3.0/features/security/auth/certificate.md
docs/v1.3.0/features/security/auth/shared-access-key.md

Mention our Arcus secret store in the API security features of the current version and the preview version.
Closes #237

docs: mention secret store in API security features

---

src/Arcus.WebApi.All/Arcus.WebApi.All.csproj
src/Arcus.WebApi.Logging.AzureFunctions/Arcus.WebApi.Logging.AzureFunctions.csproj
src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.Logging/Extensions/HttpCorrelationEnricherExtensions.cs
src/Arcus.WebApi.OpenApi.Extensions/Arcus.WebApi.OpenApi.Extensions.csproj
src/Arcus.WebApi.OpenApi.Extensions/CertificateAuthenticationOperationFilter.cs
src/Arcus.WebApi.OpenApi.Extensions/SharedAccessKeyAuthenticationOperationFilter.cs
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Security/Authentication/Certificates/X509ValidationLocation.cs
src/Arcus.WebApi.Security/Authorization/AzureManagedIdentityAuthorizationFilter.cs
src/Arcus.WebApi.Tests.Integration/Fixture/TestApiServerOptions.cs
src/Arcus.WebApi.Tests.Integration/Logging/RequestTrackingMiddlewareTests.cs
src/Arcus.WebApi.Tests.Runtimes.AzureFunction/HttpTriggerFunction.cs

Adheres the code and project warnings.

chore: adhere code and project warnings

---

build/ci-build.yml
build/nuget-release.yml
build/templates/run-integration-tests.yml
build/variables/build.yml
src/Arcus.WebApi.All/Arcus.WebApi.All.csproj
src/Arcus.WebApi.Hosting/Arcus.WebApi.Hosting.csproj
src/Arcus.WebApi.Logging.AzureFunctions/Arcus.WebApi.Logging.AzureFunctions.csproj
src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.Logging/ExceptionHandlingMiddleware.cs
src/Arcus.WebApi.OpenApi.Extensions/Arcus.WebApi.OpenApi.Extensions.csproj
src/Arcus.WebApi.OpenApi.Extensions/CertificateAuthenticationOperationFilter.cs
src/Arcus.WebApi.OpenApi.Extensions/OAuthAuthorizeOperationFilter.cs
src/Arcus.WebApi.OpenApi.Extensions/SharedAccessKeyAuthenticationOperationFilter.cs
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Tests.Core/Arcus.WebApi.Tests.Core.csproj
src/Arcus.WebApi.Tests.Integration/Arcus.WebApi.Tests.Integration.csproj
src/Arcus.WebApi.Tests.Runtimes.AzureFunction/Arcus.WebApi.Tests.Runtimes.AzureFunction.csproj
src/Arcus.WebApi.Tests.Runtimes.AzureFunction/Dockerfile
src/Arcus.WebApi.Tests.Unit/Arcus.WebApi.Tests.Unit.csproj

Upgrades towards .NET 6.
Relates to https://github.com/arcus-azure/arcus/issues/106

chore: upgrade towards net6.0

---

src/Arcus.WebApi.All/Arcus.WebApi.All.csproj
src/Arcus.WebApi.Hosting/Arcus.WebApi.Hosting.csproj
src/Arcus.WebApi.Logging.AzureFunctions/Arcus.WebApi.Logging.AzureFunctions.csproj
src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.OpenApi.Extensions/Arcus.WebApi.OpenApi.Extensions.csproj
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Tests.Unit/Logging/IServiceCollectionExtensionsTests.cs

Treat warnings as errors.
Relates to https://github.com/arcus-azure/arcus/issues/196

chore: treat warnings as errors

---

src/Arcus.WebApi.Logging.AzureFunctions/Arcus.WebApi.Logging.AzureFunctions.csproj

Follow-up PR for #312 with invalid merge.

fix: revert Arcus.WebApi.Logging.AzureFunctions.csproj to .NET 6

---

src/Arcus.WebApi.All/Arcus.WebApi.All.csproj
src/Arcus.WebApi.Hosting/Arcus.WebApi.Hosting.csproj
src/Arcus.WebApi.Logging.AzureFunctions/Arcus.WebApi.Logging.AzureFunctions.csproj
src/Arcus.WebApi.Logging.Core/Arcus.WebApi.Logging.Core.csproj
src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj
src/Arcus.WebApi.OpenApi.Extensions/Arcus.WebApi.OpenApi.Extensions.csproj
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.sln

Adds package readme project tag to project files.
Relates to https://github.com/arcus-azure/arcus/issues/209

chore: add package readme project tag

---

src/Arcus.WebApi.Logging.Core/Extensions/IServiceCollectionExtensions.cs

Proposal to make sure that we don't use deprecated extensions, but don't release a next major, too.
Relates to https://github.com/arcus-azure/arcus.templates/issues/601

chore: rethink http correlation extension

---

docs/preview/index.md

Adds introduction paragraph to the index page of the feature documentation.

docs: add introduction paragraph

---

src/Arcus.WebApi.Logging/RequestTrackingAttribute.cs

Improves the request tracking attribute with a better description that explains what can be done.
Closes #332

docs: improve request tracking attribute description

---

docs/preview/index.md
docs/versioned_docs/version-v1.6.0/index.md

Update with the same sample package as the release notes as we don't have an 'All' package anymore.

fix: update w correct sample package

---

docs/preview/03-Features/security/auth/shared-access-key.md
src/Arcus.WebApi.Security/Arcus.WebApi.Security.csproj
src/Arcus.WebApi.Security/Authentication/SharedAccessKey/Extensions/MvcOptionsExtensions.cs
src/Arcus.WebApi.Security/Authentication/SharedAccessKey/SharedAccessKeyAuthenticationAttribute.cs
src/Arcus.WebApi.Security/Authentication/SharedAccessKey/SharedAccessKeyAuthenticationFilter.cs
src/Arcus.WebApi.Tests.Integration/Security/Authentication/Fixture/InMemoryVersionedSecretProvider.cs
src/Arcus.WebApi.Tests.Integration/Security/Authentication/SharedAccessKeyAuthenticationAttributeTests.cs
src/Arcus.WebApi.Tests.Integration/Security/Authentication/SharedAccessKeyAuthenticationFilterTests.cs

Add support for versioned secrets in the shared access key authentication.

feat: add support for versioned secrets in shared access key auth

---

src/Arcus.WebApi.Logging.Core/RequestTracking/RequestTrackingTemplate.cs

Remove leftover from testing HTTP request tracking and sanitization.

chore: remove leftover testing req tracking

---

docs/preview/03-Features/correlation-azure-functions.md
docs/preview/03-Features/correlation.md

Improve HTTP correlation usage by including the logging and providing a list of required changes.

docs: more explicit http correlation usage

---

docs/preview/03-Features/correlation.md

Small typo fix, using 'receiving side'.

docs: use 'receiving side'
